security:
  basic:
    enabled: false

  spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      password: O5l@+oDqx
      url: jdbc:mysql://10.31.50.1:31705/mechanism_model?useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root